name: Construir y liberar Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear código
        uses: actions/checkout@v2

      - name: Configurar Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen
        run: docker build -t mi-imagen-docker .

      - name: Subir imagen a Docker Hub
        run: docker push mi-imagen-docker
